version: '3'

services: 

  nodeapp:
    build: 
      context: node
    container_name: nodeapp
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks: 
      - nodenetwork
    tty: true
    depends_on: 
       - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: joseclaudiodev/nginx:prod
    container_name: nginx
    networks: 
      - nodenetwork
    ports: 
      - "8080:80"
    depends_on:
      - nodeapp

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenetwork

    

networks: 
  nodenetwork:
    driver: bridge      
